app/models/settings.py
from app.extensions import db


class Settings(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True, nullable=False)
    value = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f'<Settings {self.name}>'

app/routes/main.py
import os
from flask import Blueprint, render_template, send_file, redirect, url_for, jsonify, request, flash
from app.services.settings_manager import SettingsManager
from app.services.print_service import PrintService

main_blueprint = Blueprint('main', __name__)

@main_blueprint.route('/')
def home():
    if not SettingsManager.settings_exist():
        return redirect(url_for('settings.settings'))
    
    return render_template('main.html')

@main_blueprint.route('/print/new', methods=['GET', 'POST'])
def new_print():
    if not SettingsManager.settings_exist():
        return redirect(url_for('settings.settings'))
    
    form_data = {}
    if request.method == 'POST':
        name = request.form['name']
        creator = request.form['creator']
        description = request.form['description']
        tags = request.form['tags'].split(',')
        files = request.files.getlist('files')

        success, message = PrintService.create_new_print(name, creator, description, tags, files)        
        success = False
        if success:
            flash('Print added successfully!', 'success')
            return redirect(url_for('main.home'))
        else:
            flash(f'Error adding print: {message}', 'danger')
            form_data = {
                'name': name,
                'description': description,
                'tags': tags
            }
    
    return render_template('new_print.html', form_data=form_data)


@main_blueprint.route('/api/prints', methods=['GET'])
def api_get_prints():
    '''
    api endpoint to get all print records
    returns: json response with all print records or error message if no prints found

    params: 
    page (int): page number for pagination, default is 1per_page (int): number of items per page, default is 10
    order_by (str): field to order by, default is 'name'
    order (str): order direction, 'asc' or 'desc', default is 'asc'
    '''
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 10, type=int)
    order_by = request.args.get('order_by', 'name')
    order = request.args.get('order', 'asc')
    search = request.args.get('search', None)
    tags = request.args.get('tags', None)
    if tags:
        tags = tags.split(',')
        tags = [tag.strip() for tag in tags]
        
    prints = PrintService.get_prints(search=search, tags=tags, order_by=order_by, order=order, page=page, per_page=per_page)
    if prints:
        return jsonify(prints)
    else:
        return jsonify({'error': 'An error occurred while fetching prints'}), 500
    

# API Endpoints
@main_blueprint.route('/api/print/<int:print_id>', methods=['GET'])
def api_get_print(print_id):
    '''
    api endpoint to get print data for a specific print record
    args: print_id (int): the id of the print record
    returns: json response with print data or error message if print not found
    '''    
    print_data = PrintService.get_print_data(print_id)
    if(print_data):
        return jsonify(print_data)
    else:
        return jsonify({'error': 'Print not found'}), 404
    

app/routes/settings.py
from flask import Blueprint, render_template, jsonify, request
from app.services.settings_manager import SettingsManager

settings_blueprint = Blueprint('settings', __name__)

@settings_blueprint.route('/settings')
def settings():
    #get all settings 
    settings = SettingsManager.get_all_settings()
    if(len(settings) == 0):
        #if no settings found, create default settings
        SettingsManager.set_defualt_settings()
        settings = SettingsManager.get_all_settings()

    return render_template('settings.html', settings=settings)

@settings_blueprint.route('/settings/update', methods=['POST'])
def update_settings():
    try:
        data = request.json
        for key, value in data.items():
            SettingsManager.set_setting(key, value)
        return jsonify({"success": True, "message": "Settings updated successfully"})
    except Exception as e:
        return jsonify({"success": False, "message": str(e)}), 400

app/templates/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}PFS{% endblock %}</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap/bootstrap.min.css')}}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body class="d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">PFS</a>
                
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="/print/new">Add Print</a>
                        <a class="nav-link" href="/settings">Settings</a>
                        <a class="nav-link" href="/about">About</a>
                    </div>
                </div>
                <form class="d-flex" role="search" id="formSearch">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </nav>

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </header>
    
    <main class="flex-grow-1">
        <div class="container-fluid py-3">
        {% block content %}
        {% endblock %}
        </div>  
    </main>
    
    <footer class="mt-auto py-3 bg-dark">
        <div class="container">
            <span class="text-muted">Print File System | <a href="https://devbyash.com" target="_blank">DevByAsh.com</a></span>
        </div>
    </footer>

    {% block scripts %}
    <script src="{{url_for('static', filename='js/bootstrap/bootstrap.bundle.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/viewstl/stl_viewer.min.js')}}"></script>
    {% endblock %}
</body>
</html>

app/templates/main.html
{% extends "base.html" %}

{% block title %}PFS - Main{% endblock %}

{% block content %}
    <!-- Add your main content here -->
    <h1>Welcome to PFS</h1>
    <!-- More content... -->
{% endblock %}


{% block scripts %}
    {{ super() }}  <!-- This includes any scripts from the base template -->
    <script>
        // Your unique JavaScript for the main page
        console.log("This is the main page script");
    </script>
{% endblock %}

app/templates/new_print.html
{% extends "base.html" %}

{% block title %}PFS - New Print{% endblock %}

{% block content %}
<h1>Add New Print</h1>

<form action="{{ url_for('main.new_print') }}" method="POST" enctype="multipart/form-data">
    <div class="mb-3">
        <label for="name" class="form-label" >Print Name</label>
        <input type="text" class="form-control" id="name" name="name" value="{{ form_data.name if form_data else '' }}" required>
    </div>
    <div class="mb-3">
        <label for="name" class="form-label" >Creator</label>
        <input type="text" class="form-control" id="creator" name="creator" value="{{ form_data.creator if form_data else '' }}" required>
    </div>    
    <div class="mb-3">
        <label for="description" class="form-label">Description</label>
        <textarea class="form-control" id="description" name="description" rows="3">{{ form_data.description if form_data else '' }}</textarea>
    </div>
    <div class="mb-3">
        <label for="tags" class="form-label">Tags (comma-separated)</label>
        <input type="text" class="form-control" id="tags" name="tags" value="{{ form_data.tags if form_data else '' }}">
    </div>
    <div class="mb-3">
        <label for="files" class="form-label">Print Files</label>
        <input type="file" class="form-control" id="files" name="files" multiple>
    </div>
    <button type="submit" class="btn btn-primary">Add Print</button>
</form>
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}

app/templates/settings.html
{% extends "base.html" %}

{% block title %}PFS - Settings{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow">
                <div class="card-header bg-info text-white">
                    <h2 class="mb-0">Settings</h2>
                </div>
                <div class="card-body">
                    <form id="settingsForm">
                        
                        <div class="mb-4">
                            <label for="base_path" class="form-label fw-bold">Print Storage Base Path</label>
                            <div class="input-group">
                                <span class="input-group-text"><i class="bi bi-folder"></i></span>
                                <input type="text" class="form-control" id="base_path" name="base_path" aria-describedby="base_pathHelp" value="{{ settings.base_path }}">
                            </div>
                            <div id="base_pathHelp" class="form-text text-muted mt-2">
                                <i class="bi bi-info-square"></i> The base path for where print files are saved.
                            </div>
                        </div>

                        <div class="mb-4">
                            <label for="print_dir_naming_pattern" class="form-label fw-bold">Print Directory Naming Pattern</label>
                            <div class="input-group">
                                <span class="input-group-text"><i class="bi bi-folder"></i></span>
                                <input type="text" class="form-control" id="print_dir_naming_pattern" name="print_dir_naming_pattern" aria-describedby="print_dir_naming_patternHelp" value="{{ settings.print_dir_naming_pattern }}">
                            </div>
                            <div id="print_dir_naming_patternHelp" class="form-text text-muted mt-2">
                                <i class="bi bi-info-square"></i> {creator}/{name}#{id}
                            </div>
                        </div>

                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary">
                                <i class="bi bi-floppy"></i> Save Settings
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block scripts %}
    {{ super() }}  <!-- This includes any scripts from the base template -->
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const form = document.getElementById('settingsForm');
            form.addEventListener('submit', function(e) {
                e.preventDefault();
                
                const formData = new FormData(form);
                const data = Object.fromEntries(formData.entries());

                fetch('/settings/update', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify(data),
                })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        alert('Settings saved successfully!');
                    } else {
                        alert('Error saving settings: ' + data.message);
                    }
                })
                .catch((error) => {
                    console.error('Error:', error);
                    alert('An error occurred while saving settings.');
                });
            });
        });
    </script>
{% endblock %}